esphome:
  name: 433-controller
  friendly_name: 433-controller
  min_version: 2024.11.0
  name_add_mac_suffix: false
  # on_boot: 
  #   then:
  #     - remote_transmitter.transmit_raw: 
  #         code: [500, -200, 200, -600, 100, -600, 200, -600, 600, -200, 600, -200, 600, -200, 200, -600, 600, -200, 600, -200, 200, -600, 200, -600, 200, 
  #               -600, 600, -200, 200, -600, 600, -200, 200, -600, 600, -200, 200, -600, 200, -600, 200, -600, 200, -600, 600, -200, 600, -200, 200]
  #         repeat:
  #           times: 6
esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret basement-water-sensor_hassio_encryption_key

ota:
  - platform: esphome
    password: !secret ota_update_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "433-controller-fallback"
    password: !secret captive_portal_password

captive_portal:

# Relay BLE devices to HASSIO
esp32_ble_tracker:
bluetooth_proxy:
  active: true

sensor:
  - platform: wifi_signal
    name: "WiFi Strength"
    disabled_by_default: true
    update_interval: 60s

# remote_receiver:
#   pin: 
#     number: GPIO25
#     inverted: True
#     mode: 
#       pullup: True
#       input: True
#   dump: raw 

remote_transmitter:
  pin: GPIO26
  carrier_duty_percent: 100%

button:
  - platform: template
    id: doorbell_chime
    name: Doorbell Chime
    icon: mdi:bell
    on_press: 
      then:
        - remote_transmitter.transmit_raw:
            code: [500, -200, 200, -600, 100, -600, 200, -600, 600, -200, 600, -200, 600, -200, 200, -600, 
                   600, -200, 600, -200, 200, -600, 200, -600, 200, -600, 600, -200, 200, -600, 600, -200, 
                   200, -600, 600, -200, 200, -600, 200, -600, 200, -600, 200, -600, 600, -200, 600, -200, 200]
            repeat:
              times: 3
