name: Sync with Gist

on:
  workflow_dispatch:

jobs:
  sync-with-gist:
    name: 'Sync ESPHome directory with Gist'
    runs-on: ubuntu-20.04

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Sync files'
        uses: sp00ls/action-gist-repo-sync@main
        with:
          gist_token: ${{ secrets.GIST_TOKEN }}
          gist_id: 3754e8459405a990af35c7d4be3583a8
          source_path: esphome
#jobs:
#  files-modified:
#    name: 'Check if files changed'
#    runs-on: ubuntu-latest
#    outputs:
#      files_changes: ${{ steps.changed-files.outputs.any_changed }}
#
#    steps:
#      - name: 'Checkout repository'
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      - name: 'Detect modified files'
#        id: changed-files
#        uses: tj-actions/changed-files@v39
#        with:
#          files: 'esphome/'
#      - name: 'Print no files modified'
#        if: steps.changed-files.outputs.any_changed == 'false'
#        run: echo "No file(s) have been modified"
#
#      - name: 'Print modified files'
#        if: steps.changed-files.outputs.any_changed == 'true'
#        run: |
#          echo "Modified:"
#          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
#            echo "$file"
#          done
#
#  sync-gist:
#    name: 'Sync changed files to Gist'
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: 'Checkout this repository'
#        uses: actions/checkout@v4
#        with:
#          path: 'ha_config'
#      - name: 'Checkout Gist repository'
#        uses: actions/checkout@v4
#        repository: ''