name: Sync with Gist
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync-esphome-with-gist:
    name: 'Sync ESPHome directory with Gist'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Sync files'
        uses: sp00ls/action-gist-repo-sync@main
        with:
          gist_token: ${{ secrets.GIST_TOKEN }}
          gist_id: 3754e8459405a990af35c7d4be3583a8
          source_path: esphome